Css refactoring
node-girls-australia/nodegirls.com.au pull request #9
Opened 2016-12-21 03:34 UTC by ReenaRajani

Updates based on the comments as discussed

2017-01-11 10:30 UTC, ButenkoT requested changes

2017-01-11 10:30 UTC, ButenkoT commented on css/materialize.css
> +  margin: 10px 0px;
When we have a someone's library we are not changing things in it. That is for we have our own css where we can overwrite some particular pieces  that are suitable for us. Can you move it to `styles.css` file, please. 
`.chip{
 margin: 10px 0px;
}`

2017-01-11 10:30 UTC, ButenkoT commented on contacts.html
> +                    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button" style="margin:0.5em 1em"></div>
would be better if you do it in `style.css` file, so we do not touch 3d party code.

2017-01-25 04:17 UTC, ReenaRajani commented
@ButenkoT . this is done

2017-01-27 02:21 UTC, ButenkoT approved these changes

2017-01-27 02:21 UTC, ButenkoT commented
All looks good, I guess we can merge it

2017-01-27 02:23 UTC, merged